### ISSUE TITLE
M3u8 with qualities in Ios can't play .show 'Failed to load video: The operation could not be completed'

### ISSUE THREAD

**Issue by mayhninkyidkmads** [zezo357/flutter_meedu_videoplayer#100]

**Comment by zezo357** [comment]
Please provide full logs in the issue not the title, and a url to test on

**Comment by mayhninkyidkmads** [comment]
url is example of M3u8 with qualities 



![viber_image_2023-05-30_17-02-58-779](https://github.com/zezo357/flutter_meedu_videoplayer/assets/115967295/e03087ef-fbd8-46d0-8a28-7b0e8e3cee58)

**Comment by zezo357** [comment]
Can you share app logs?

**Comment by mayhninkyidkmads** [comment]
flutter: PlatformException(VideoError, Failed to load video: The operation could not be completed, null, null)
flutter:
flutter: Fit is BoxFit.fill

**Comment by zezo357** [comment]
And the url you are testing is the default one right?



Can you try it with media_kit enabled?

**Comment by zezo357** [comment]
Right now I am busy, I can't test it I will try to test it whenever I have time

**Comment by mayhninkyidkmads** [comment]
I understand. Thank you for replying me. I'll also try my issue.

**Comment by zezo357** [comment]
use media_kit for ios since video_player doesnt seem to support m3u8 on ios.


follow these steps 
### iOS (replace original video_player with media_kit one)

1. The minimum supported iOS version is 13.0, so the target needs to be set IPHONEOS_DEPLOYMENT_TARGET to 13.0 in `ios\Runner.xcodeproj\project.pbxproj`
2. Just add this package in case you set iosUseMediaKit to true in initMeeduPlayer
```yaml
dependencies:
  ...
  media_kit_libs_ios_video: ^1.0.4         # iOS package for video (& audio) native libraries.
```
